# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OneEnvCli < Formula
  desc ""
  homepage "https://github.com/ericflores108"
  version "0.8"

  on_macos do
    url "https://github.com/ericflores108/one-env-cli/releases/download/v0.8/one-env-cli_Darwin_all.tar.gz"
    sha256 "7d07beb5e75a98de7de767565a3208d674089f1be1efafe509b7973c77d8ffa2"

    def install
      bin.install "one-env-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ericflores108/one-env-cli/releases/download/v0.8/one-env-cli_Linux_x86_64.tar.gz"
      sha256 "5abbbeeebaa10f6c97ac0141988f94925e2e5bcdefe4b8d94f397b5e0535d206"

      def install
        bin.install "one-env-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericflores108/one-env-cli/releases/download/v0.8/one-env-cli_Linux_arm64.tar.gz"
      sha256 "0f29332bdcac04d17e3c77c0784809e8cf8539372c3acac43a1cf7bff6ce82ff"

      def install
        bin.install "one-env-cli"
      end
    end
  end
end
