# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OneEnvCli < Formula
  desc ""
  homepage "https://github.com/ericflores108"
  version "1.1"

  on_macos do
    url "https://github.com/ericflores108/one-env-cli/releases/download/v1.1/one-env-cli_Darwin_all.tar.gz"
    sha256 "6c53f119d7da819e51d118cacbe6c37339fbfe41d5fc7d001f1c4759990808cd"

    def install
      bin.install "one-env-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ericflores108/one-env-cli/releases/download/v1.1/one-env-cli_Linux_x86_64.tar.gz"
        sha256 "834abcaaa67a19394bdca3c9f36504c3ea3f3b1b5693fb5b76a3b436db67d628"

        def install
          bin.install "one-env-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ericflores108/one-env-cli/releases/download/v1.1/one-env-cli_Linux_arm64.tar.gz"
        sha256 "b6b5cfe62e132ae6d9549e0cc2022feb57bd046c9b8ad1620cba182444fb02ef"

        def install
          bin.install "one-env-cli"
        end
      end
    end
  end
end
